# Set the build language to python
language: python

# Set the python version to 3.6 and 3.7
python:
  - '3.6'
  - '3.7'

env:
  global:
    - GAMS=24.9
    - GAMS_URL=https://d37drm4t2jghv5.cloudfront.net/distributions/24.9.2/linux/linux_x64_64_sfx.exe


before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p $MINICONDA
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Edit the environment.yml file for the target Python version
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml

  # Install GAMS
  - wget -N $GAMS_URL -O gams.zip
  - unzip -qu gams.zip -d $HOME
  - ln -s $HOME/gams${GAMS}_linux_x64_64_sfx $HOME/gams
  - export GAMSPATH="$HOME/gams"
  - export PATH="$GAMSPATH:$PATH"
  - cd $HOME/gams
  - gamsinst -a
  - cd -

# Install required dependencies
install:
  - conda env create -q -f environment.yml
  - source activate darko
  - python setup.py develop

# Run the tests
script:
  - coverage run -m pytest --cov

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
