name: darko

dependencies:
  - python >= 3.7
  - future >= 0.18.2
  - click >= 3.3
  - numpy >= 1.18.1
  - scipy >= 1.4.1
  - matplotlib >= 1.5.1
  - pandas >= 1.0.3
  - xlrd = 1.2
  - xarray >= 0.11
  - netcdf4
  - pyyaml >= 5.1
  - pytest
  - xlsxwriter
  - pip
  - pip:
    - gdxcc
    - gamsxcc
    - optcc
    - setuptools_scm
    - mplfinance
    - pytest-cov
    - codecov
